version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: personal-telegram-bot
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount config for easy updates
      - ./config:/app/config
      # Mount data for persistence
      - ./data:/app/data
      # Mount logs for debugging
      - ./logs:/app/logs
    ports:
      - "8000:8000"  # For health checks
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
