service: personal-system-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  stage: prod
  memorySize: 256
  timeout: 30
  environment:
    # Core Database (Free Tier)
    CORE_SUPABASE_URL: ${env:CORE_SUPABASE_URL}
    CORE_SUPABASE_ANON_KEY: ${env:CORE_SUPABASE_ANON_KEY}
    # Main Database (Self-hosted)
    MAIN_SUPABASE_URL: ${env:MAIN_SUPABASE_URL}
    MAIN_SUPABASE_ANON_KEY: ${env:MAIN_SUPABASE_ANON_KEY}
    # ElevenLabs
    ELEVENLABS_API_KEY: ${env:ELEVENLABS_API_KEY}
    ELEVENLABS_VOICE_ID: ${env:ELEVENLABS_VOICE_ID, '21m00Tcm4TlvDq8ikWAM'}
    # Telegram
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}
    TELEGRAM_CHAT_ID: ${env:TELEGRAM_CHAT_ID}
    # Gitea
    GITEA_URL: ${env:GITEA_URL}
    GITEA_TOKEN: ${env:GITEA_TOKEN}
    GITEA_WEBHOOK_SECRET: ${env:GITEA_WEBHOOK_SECRET}
    # Coolify
    COOLIFY_URL: ${env:COOLIFY_URL}
    COOLIFY_API_TOKEN: ${env:COOLIFY_API_TOKEN}
    COOLIFY_PROJECT_UUID: ${env:COOLIFY_PROJECT_UUID}
    COOLIFY_APPLICATION_UUID: ${env:COOLIFY_APPLICATION_UUID}

functions:
  # Daily Summary (existing)
  daily-summary:
    handler: daily_summary_lambda.lambda_handler
    events:
      - schedule:
          rate: cron(0 12 * * ? *)  # Daily at 12 PM UTC
          enabled: true
    environment:
      TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${env:TELEGRAM_CHAT_ID}

  # CI/CD Webhook Handler
  gitea-webhook-handler:
    handler: gitea_webhook_handler.lambda_handler
    timeout: 300  # 5 minutes for deployment
    memorySize: 512
    events:
      - http:
          path: /webhook/gitea
          method: post
          cors: true

  # CI/CD Orchestrator
  cicd-orchestrator:
    handler: cicd_orchestrator.lambda_handler
    timeout: 900  # 15 minutes for full pipeline
    memorySize: 1024

  # Coolify Deployer
  coolify-deployer:
    handler: coolify_deployer.lambda_handler
    timeout: 300
    memorySize: 512
    environment:
      COOLIFY_URL: ${env:COOLIFY_URL}
      COOLIFY_API_TOKEN: ${env:COOLIFY_API_TOKEN}
      COOLIFY_PROJECT_UUID: ${env:COOLIFY_PROJECT_UUID}
      COOLIFY_APPLICATION_UUID: ${env:COOLIFY_APPLICATION_UUID}

  # Daily Voice Message (new)
  daily-voice-message:
    handler: daily_voice_lambda.lambda_handler
    timeout: 120  # Longer timeout for voice generation
    memorySize: 512  # More memory for voice processing
    events:
      - schedule:
          rate: cron(0 7 * * ? *)  # Daily at 7 AM UTC
          enabled: true

  # Voice Content Generator (utility)
  voice-content-generator:
    handler: voice_content_generator.lambda_handler
    timeout: 60

  # ElevenLabs TTS (utility)
  elevenlabs-tts:
    handler: elevenlabs_tts.lambda_handler
    timeout: 120
    memorySize: 512

  # Data Sync Manager
  data-sync-manager:
    handler: data_sync_manager.lambda_handler
    events:
      - schedule:
          rate: cron(0 */4 * * ? *)  # Every 4 hours
          enabled: true

  # Data Lifecycle Manager
  data-lifecycle-manager:
    handler: data_lifecycle_manager.lambda_handler
    events:
      - schedule:
          rate: cron(0 2 * * 0)  # Weekly on Sunday at 2 AM UTC
          enabled: true

  # Data Monitor
  data-monitor:
    handler: data_monitor.lambda_handler
    events:
      - schedule:
          rate: cron(0 9 * * ? *)  # Daily at 9 AM UTC
          enabled: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer: true

package:
  patterns:
    - '!**/*.pyc'
    - '!**/__pycache__'
    - '!**/node_modules/**'
    - '!**/.git/**'
    - '!README.md'
    - '!serverless.yml'
    - '!requirements.txt'
    - '!deploy.sh'
    - '!run.sh'
    - '!multi_tier_config.yaml'
    - '!multi_tier_config.local.yaml'
