# Coolify Deployment Configuration
version: '1'

services:
  personal-system:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile
    environment:
      - CORE_SUPABASE_URL=${CORE_SUPABASE_URL}
      - CORE_SUPABASE_ANON_KEY=${CORE_SUPABASE_ANON_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - ELEVENLABS_VOICE_ID=${ELEVENLABS_VOICE_ID}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
