version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: personal-telegram-bot
    restart: unless-stopped
    environment:
      # Telegram Bot Configuration
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_USER_ID=${TELEGRAM_USER_ID}
      
      # API Keys (Optional)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      
      # Health Check Configuration
      - HEALTH_CHECK_PORT=8000
      
      # Python Configuration
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      
    volumes:
      # Persistent data storage
      - bot_data:/app/data
      - bot_logs:/app/logs
      - bot_config:/app/config
      
    ports:
      - "8000:8000"
      
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

# Named volumes for persistent storage
volumes:
  bot_data:
    driver: local
  bot_logs:
    driver: local
  bot_config:
    driver: local
