elevenlabs:
  api_key: sk_9382e4b7a49fa13e8334898360f9e3bd75ee67cfb27492fc
  enable_speech_to_text: true
  enable_text_to_speech: false
  voice_id: 21m00Tcm4TlvDq8ikWAM
  language: auto  # Only English and Russian supported
  supported_languages: ["en", "ru"]  # ONLY English and Russian - no other languages
features:
  daily_summary: true
  health_tracking: true
  journal_integration: true
  learning_tracking: true
  shadow_work_tracking: true
  system_status: true
  task_management: true
integrations:
  enable_external_apis: false
  finance_api_key: Z0FBQUFBQm9xYkoxMVNTRmNSbFdydDBTZTI1UGhSdmhlelFLbi1tQ29XdHVjbEFyeFhPWDEtbXB2MW1kWGRqcHhBTUczQWxkM2dJREpQX0RNVHpZbXZUQVRHZEFUbGRtQkRiSEtEVElNMnhGZDFPSThsdlVfa0Y5X0RxREpBcV9DZ1dRZ28wN3A5NmR2UzB1ZGVNYTNDdm5tT3h1V2lJZnVpeWNId3JLVFB1cGduOGJMcmNiWll4QlFZdERad3dYMTZCSThubmE3UC12MWpKYmdGWmlObXRBc3dvYXhaM0tHWGNfaVpZeG9DeEQzMC03SFZDdUhfSS14OW5aMHpDYks5LW9qRUpMNzJUbmFSZmxOemU3VWhXT3Rrd09YTTQ0QV9MUHNfc3F6YjV5czRLVmNFd2U0ZWc9
  health_api_key: Z0FBQUFBQm9xYkoxMVNTRmNSbFdydDBTZTI1UGhSdmhlelFLbi1tQ29XdHVjbEFyeFhPWDEtbXB2MW1kWGRqcHhBTUczQWxkM2dJREpQX0RNVHpZbXZUQVRHZEFUbGRtQkRiSEtEVElNMnhGZDFPSThsdlVfa0Y5X0RxREpBcV9DZ1dRZ28wN3A5NmR2UzB1ZGVNYTNDdm5tT3h1V2lJZnVpeWNId3JLVFB1cGduOGJMcmNiWll4QlFZdERad3dYMTZCSThubmE3UC12MWpKYmdGWmlObXRBc3dvYXhaM0tHWGNfaVpZeG9DeEQzMC03SFZDdUhfSS14OW5aMHpDYks5LW9qRUpMNzJUbmFSZmxOemU3VWhXT3Rrd09YTTQ0QV9MUHNfc3F6YjV5czRLVmNFd2U0ZWc9
  weather_api_key: Z0FBQUFBQm9xYkoxMVNTRmNSbFdydDBTZTI1UGhSdmhlelFLbi1tQ29XdHVjbEFyeFhPWDEtbXB2MW1kWGRqcHhBTUczQWxkM2dJREpQX0RNVHpZbXZUQVRHZEFUbGRtQkRiSEtEVElNMnhGZDFPSThsdlVfa0Y5X0RxREpBcV9DZ1dRZ28wN3A5NmR2UzB1ZGVNYTNDdm5tT3h1V2lJZnVpeWNId3JLVFB1cGduOGJMcmNiWll4QlFZdERad3dYMTZCSThubmE3UC12MWpKYmdGWmlObXRBc3dvYXhaM0tHWGNfaVpZeG9DeEQzMC03SFZDdUhfSS14OW5aMHpDYks5LW9qRUpMNzJUbmFSZmxOemU3VWhXT3Rrd09YTTQ0QV9MUHNfc3F6YjV5czRLVmNFd2U0ZWc9
logging:
  backup_count: 5
  file: ./logs/bot.log
  level: INFO
  max_size: 10MB
n8n:
  api_key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3OTcyNWI2NC04Y2MzLTQ1MzAtODhkMC0zOGM0NmY4NmUyYWIiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwiaWF0IjoxNzU3NTc5ODgwLCJleHAiOjE3NjAxMzAwMDB9.kDSuRysoK1uJntS-rcIzbBjia60zo0kv0wT5T1btniE
  base_url: https://automationus.tangovision.dev
  fallback_enabled: true
  openai:
    api_key: your_openai_api_key_here
    max_tokens: 1000
    model: gpt-4o
    temperature: 0.3
  password: ''
  timeout: 10
  username: ''
  webhook_path: multilingual-intent
notifications:
  daily_reminder: 09:00
  evening_checkin: '21:00'
  shadow_work_reminder: '18:00'
  weekly_review: sunday 20:00
openai:
  api_key: Z0FBQUFBQm9xYkoxMVNTRmNSbFdydDBTZTI1UGhSdmhlelFLbi1tQ29XdHVjbEFyeFhPWDEtbXB2MW1kWGRqcHhBTUczQWxkM2dJREpQX0RNVHpZbXZUQVRHZEFUbGRtQkRiSEtEVElNMnhGZDFPSThsdlVfa0Y5X0RxREpBcV9DZ1dRZ28wN3A5NmR2UzB1ZGVNYTNDdm5tT3h1V2lJZnVpeWNId3JLVFB1cGduOGJMcmNiWll4QlFZdERad3dYMTZCSThubmE3UC12MWpKYmdGWmlObXRBc3dvYXhaM0tHWGNfaVpZeG9DeEQzMC03SFZDdUhfSS14OW5aMHpDYks5LW9qRUpMNzJUbmFSZmxOemU3VWhXT3Rrd09YTTQ0QV9MUHNfc3F6YjV5czRLVmNFd2U0ZWc9
  enable_voice_transcription: true
  max_file_size: 25
  model: whisper-1
  language: auto  # Only English and Russian supported
  supported_languages: ["en", "ru"]  # ONLY English and Russian - no other languages
  supported_formats:
  - mp3
  - mp4
  - mpeg
  - mpga
  - m4a
  - wav
  - webm
paths:
  automation_scripts: ../../automation/scripts/
  base_path: ../../
  journal: ../../core/knowledge/journal/
  notes: ../../core/knowledge/notes/
  shadow_work: ../../core/identity/shadow_work.md
  templates: ../../templates/
privacy:
  auto_backup: true
  backup_frequency: daily
  encrypt_sensitive_data: true
  respect_private_markers: true
serverless:
  api_key: ''
  enable_serverless_transcription: true
  transcription_url: https://1pubjgwn81.execute-api.eu-central-1.amazonaws.com/prod/voice-transcription
storage:
  backup_dir: ./data/backups/
  cache_dir: ./data/cache/
  data_dir: ./data/storage/
  encryption_key_file: ./data/keys/encryption.key
telegram:
  admin_users:
  - 71597815
  allowed_users:
  - 71597815
  bot_token: 8433928834:AAEVArfPyUMqh4z_mYLP3NMxkBQVmH3Up_4
