version: '3.8'

services:
  personal-api:
    build: .
    container_name: personal-api
    restart: unless-stopped
    environment:
      # API Configuration
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - ENVIRONMENT=production
      
      # Database Configuration
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      
      # Authentication
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - API_KEY=${API_KEY}
      
      # External APIs
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      
    volumes:
      # Persistent data storage
      - api_data:/app/data
      - api_logs:/app/logs
      - api_config:/app/config
      
    ports:
      - "8000:8000"
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

# Named volumes for persistent storage
volumes:
  api_data:
    driver: local
  api_logs:
    driver: local
  api_config:
    driver: local
